trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout code
- checkout: self
  displayName: 'Checkout repository'

# Step 2: List files (helps confirm Dockerfile path)
- script: |
    echo "Current directory: $(Build.SourcesDirectory)"
    ls -la
  displayName: 'List files in workspace'

# Step 3: Build Docker image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      adhitya14/memoriai-cognitive:latest

# Step 4: Verify Docker before pushing
- script: |
    docker --version
    docker images
  displayName: 'Verify Docker environment'

# Step 5: Push image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
