trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1 — Checkout repository
- checkout: self
  displayName: 'Checkout repository'

# Step 2 — Debug: Print directory and show Dockerfile
- script: |
    echo "Current working directory:"
    pwd
    echo "Listing files recursively (max 3 levels):"
    find $(Build.SourcesDirectory) -maxdepth 3
  displayName: 'Debug: Show folder structure'

# Step 3 — Push Docker Image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      adhitya14/memoriai-cognitive:latest
      latest

