trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout
- checkout: self
  displayName: 'Checkout repository'

# Step 2: Build Docker Image (with full tag)
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      adhitya14/memoriai-cognitive:latest

# Step 3: Push Docker Image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
