trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout code
- checkout: self
  displayName: 'Checkout repository'

# Step 2: List files for confirmation
- script: |
    echo "Verifying current directory:"
    pwd
    ls -la
  displayName: 'Verify Dockerfile presence'

# Step 3: Build the Docker image with the correct tag
- task: Docker@2
  displayName: 'Build Docker Image (adhitya14/memoriai-cognitive)'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      adhitya14/memoriai-cognitive:latest

# Step 4: Verify image exists before push
- script: |
    echo "Listing Docker images..."
    docker images
  displayName: 'Check local Docker images'

# Step 5: Push image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
