trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1 — Checkout repository
- checkout: self
  displayName: 'Checkout repository'

# Step 2 — Build Docker Image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      latest

# Step 3 — Push Docker Image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
