trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1 — Checkout repo
- checkout: self
  displayName: 'Checkout repository'

# Step 2 — Verify files
- script: |
    echo "Verifying Dockerfile path..."
    ls -la $(Build.SourcesDirectory)
  displayName: 'Verify workspace contents'

# Step 3 — Build Docker image
- task: Docker@2
  displayName: 'Build Docker Image (adhitya14/memoriai-cognitive)'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      adhitya14/memoriai-cognitive:latest

# Step 4 — Check image list
- script: |
    echo "Images after build:"
    docker images
  displayName: 'List Docker Images'

# Step 5 — Push to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
