trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout code
- checkout: self
  displayName: 'Checkout repository'

# Step 2: List files to confirm Dockerfile presence
- script: |
    echo "Checking current directory..."
    pwd
    ls -la
  displayName: 'Verify workspace contents'

# Step 3: Build Docker image (tag explicitly)
- task: Docker@2
  displayName: 'Build Docker Image with Tag'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      adhitya14/memoriai-cognitive:latest

# Step 4: Verify Docker image built successfully
- script: |
    echo "Listing built images:"
    docker images
  displayName: 'Check built images'

# Step 5: Push to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'adhitya14/memoriai-cognitive'
    command: push
    tags: |
      latest
